name: jastipkuy
description: A new Flutter project.

# Ensure that the Dart SDK constraint includes version 2.17.0 or higher
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
